-------------------------
-- Traditional Chinese Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140815
-------------------------
localization_zh_rTW_table = {
    calories_table={
        {str="≈1個茶葉蛋",	calories=96},
        {str="≈1片麵包",	calories=100},
        {str="≈1瓶冰紅茶",	calories=112},
        {str="≈1個煎蛋",	calories=118},
        {str="≈2串羊肉串",	calories=124},
        {str="≈1罐可樂",	calories=153},
        {str="≈3串羊肉串",	calories=186},
        {str="≈2個茶葉蛋",	calories=192},
        {str="≈2片麵包",	calories=200},
        {str="≈1碗米飯",	calories=210},
        {str="≈1個饅頭",	calories=221},
        {str="≈1根冰糖葫蘆",	calories=223},
        {str="≈2瓶冰紅茶",	calories=224},
        {str="≈1包小薯條",	calories=224},
        {str="≈1個蛋黄派",	calories=224},
        {str="≈2個煎蛋",	calories=236},
        {str="≈4串羊肉串",	calories=248},
        {str="≈1個漢堡",	calories=260},
        {str="≈1根油條",	calories=270},
        {str="≈1個肉包子",	calories=272},
        {str="≈3個茶葉蛋",	calories=288},
        {str="≈1個甜筒",	calories=290},
        {str="≈3片麵包",	calories=300},
        {str="≈2罐可樂",	calories=306},
        {str="≈1包中薯條",	calories=328},
        {str="≈3個煎蛋",	calories=354},
        {str="≈1個蛋塔",	calories=375},
        {str="≈4片麵包",	calories=400},
        {str="≈1包大薯條",	calories=402},
        {str="≈2碗米飯",	calories=420},
        {str="≈2個饅頭",	calories=442},
        {str="≈2根冰糖葫蘆",	calories=446},
        {str="≈1個蛋黄派",	calories=448},
        {str="≈1包速食麵",	calories=470},
        {str="≈5片麵包",	calories=500},
        {str="≈1盤蛋炒飯",	calories=516},
        {str="≈2個漢堡",	calories=520},
        {str="≈2根油條",	calories=540},
        {str="≈2個肉包子",	calories=544},
        {str="≈2個甜筒",	calories=580},
        {str="≈1碗速食麵",	calories=581},
        {str="≈1碗牛肉拉麵",	calories=593},
        {str="≈10串羊肉串",	calories=620},
        {str="≈3碗米飯",	calories=630},
        {str="≈3個饅頭",	calories=663},
        {str="≈2個蛋塔",	calories=750},
        {str="≈3根油條",	calories=810},
        {str="≈3個肉包子",	calories=816},
    },

    ok='OK',

    hour='ч.',
    minute='мин.',
    month='month',
    day='day',
    step="step",
    km='км',
    minute_format='%d мин.',
    hour_minute_format='%d ч. %d мин.',
    hour_format='%d ч.',

    welcome_use="Привет, я Ваш браслет",
    last_week_walked_format='За последнюю неделю Вы прошли шагов: %d',
    last_week_walked_info_format='Пройдено %d км, сожжено %d ккал.',
    last_month_walked_format='За последний месяц Вы прошли шагов: %d',
    last_month_walked_info_format='Пройдено %d км, сожжено %d ккал.',

    get_over_format=", about %d gram of fat.",
    click_to_get_help="Инструкция по эксплуатации",
    take_a_walk="Take a walk with Mi Band.",
    take_a_walk_info="Браслет будет отслеживать вашу деятельность и поможет быть здоровыми",
    unlock_hint="Разблокировка устройства браслетом",
    unlock_hint_info="Скажите до свидания старым временам",
    no_data_hint_0="Продолжайте двигаться, сделайте спорт частью своей жизни",
    no_data_hint_1="Хотите быть счастливым? Просто запустите.",
    no_data_hint_2="Cardio workout will make you light and fresh every day! ",
    no_data_hint_3="A normal adult spends 15%-20% of total sleep time in deep sleep stage. ",
    not_binded_hint="Браслет не подключен",
    new_record_info="WoW! You just broke a record in walking.",
    new_record_format="Новый рекорд, %d шаг., %s %d",
    today_goal_reached="Congrats! You have achieved your goal today. ",
    week_continue_reach_goal="You have achieved your goal every day for an entire week! What an awesome week!",
    challenge_format="You have achieved your goal for %d days!",
    personal_best_format="Your highest record is %d days!",
    active_time_format_0="%d мин.",
    active_time_format_1="%d ч.",
    active_time_format_2="%d ч. %d мин.",
    activie_run_format_0="Ran %s. Good job!",
    activie_run_format_1="Ran %s. You are doing fantastic!",
    activie_run_format_2="Ran %s, Incredible endurance!",
    activie_run_consumed="Сожжено %d ккал. %s",

    get_distance_format=", всего из %d м.",
    activity_walk_format="%s пройдено %d шаг. %s",
    activity_walk_consumed_format="Сожжено %d ккал. %s",

    activity_activity_format="%s %s work out %s",
    last_night_sleeped_good_format="Last night, you slept for %s. What a great sleep!",
    last_night_sleeped_normal_format="Last night, you slept for %s.",
    deep_sleep_format="Глубокий сон был %s",

    battery_low_info="Низкое питание браслета. Поставьте на зарядку.",
    battery_very_low_info="Подключите на зарядку",

    cannot_find_bracelet="Не удается найти браслет?",
    cannot_find_bracelet_info="Убедитесь что браслет заряжен и находится возле устройства",

    challenge_to_get="%s days from making a new record!",
    record_reach_max="You have hit your highest record!",
    new_record_born="Новый рекорд!",
}